### ISSUE TITLE
Package name clash

### ISSUE THREAD

**Issue by kuba** [mmontone/acme#1]
Hey, @mmontone :). I've started working on the https://github.com/letsencrypt/lets-encrypt-preview in October last year and since the beginning I was aiming to publish the implementation of [the ACME protocol specification](http://letsencrypt.github.io/acme-spec/) under Python "acme" package. Unfortunately, today, while preparing the package, I've seen your https://pypi.python.org/pypi/acme... Since the rename commit (3a681758ee74fafa085d64159fe253a495e9e04a) and PyPI upload is quite recent, I was wondering if there is any chance you could rename your project once again and transfer the PyPI package ownerhsip, please? :) Me personally, and the the [Let's Encrypt Project](https://letsencrypt.org) would eternally owe you!

cc: @jdkasten, Let's Encrypt Client Lead

**Comment by mmontone** [comment]
Ok. That could be done. What about your renaming your project? Something
like acme-spec, or acme-certificate wouldn't work?

**Comment by kuba** [comment]
Thanks for a quick reply @mmontone, that would be awesome! My PyPI username is "kuba", could you please add me as an owner at https://pypi.python.org/pypi?:action=role_form&package_name=acme? :) 

While, obviously, "acme-spec" is technically possible, it will be really confusing for users and developers, especially if the PyPI project name is different than Python module name (making it also impossible to have both your project and letsencrypt installed at the same time)... "ACME" name has been picked up a long time ago as far as I know.

I'm really sorry for the inconvenience! I'll make sure to include your name in the credits :)

**Comment by kuba** [comment]
Friendly ping :) Our planned mid-2015 launch is quickly approaching... Would it be possible to sort it out ASAP? Thanks!

**Comment by mmontone** [comment]
I've just added you as owner

**Comment by kuba** [comment]
Thank you very much @mmontone, that's awesome :)

cc: @jdkasten
